import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from fpdf import FPDF

from config import settings


class _ReportPDF(FPDF):
    """Custom PDF with header/footer for PersonaShield AI."""

    def __init__(self, generated_at: str) -> None:
        super().__init__()
        self._generated_at = generated_at

    def header(self) -> None:
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(30, 60, 120)
        self.cell(0, 12, "PersonaShield AI", new_x="LMARGIN", new_y="NEXT", align="C")
        self.set_font("Helvetica", "", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, f"Identity Verification & Deepfake Analysis Report  |  {self._generated_at}", new_x="LMARGIN", new_y="NEXT", align="C")
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(6)

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(140, 140, 140)
        self.cell(0, 10, f"Generated by PersonaShield AI  |  {self._generated_at}  |  Page {self.page_no()}", align="C")

    def section_title(self, title: str) -> None:
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(30, 60, 120)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)

    @staticmethod
    def _sanitize(text: str) -> str:
        replacements = {
            "\u2014": "--", "\u2013": "-", "\u2018": "'", "\u2019": "'",
            "\u201c": '"', "\u201d": '"', "\u2026": "...", "\u2022": "*",
            "\u00b7": "*", "\u2032": "'", "\u2033": '"',
        }
        for k, v in replacements.items():
            text = text.replace(k, v)
        return text.encode("latin-1", errors="replace").decode("latin-1")

    def section_body(self, text: str) -> None:
        self.set_font("Helvetica", "", 10)
        self.multi_cell(0, 6, self._sanitize(text))
        self.ln(3)

    def score_bar(self, label: str, value: float, max_val: float = 100.0) -> None:
        self.set_font("Helvetica", "", 10)
        self.cell(55, 8, f"{label}: {value:.1f}%")
        x = self.get_x()
        y = self.get_y()
        bar_w = 100
        bar_h = 6
        # Background
        self.set_fill_color(220, 220, 220)
        self.rect(x, y + 1, bar_w, bar_h, "F")
        # Fill
        ratio = min(value / max_val, 1.0)
        if value > 70:
            self.set_fill_color(220, 50, 50)
        elif value > 40:
            self.set_fill_color(240, 180, 50)
        else:
            self.set_fill_color(60, 180, 75)
        self.rect(x, y + 1, bar_w * ratio, bar_h, "F")
        self.ln(10)


def generate_report(
    analysis_id: str,
    deepfake_score: float,
    face_match_score: Optional[float],
    voice_match_score: Optional[float],
    authenticity_score: float,
    explanation: str,
    is_deepfake: bool,
) -> str:
    """Generate a professional PDF report and return its file path."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    pdf = _ReportPDF(generated_at=now)
    pdf.add_page()

    # 1. Analysis Summary
    pdf.section_title("1. Analysis Summary")
    verdict = "LIKELY DEEPFAKE / MANIPULATED" if is_deepfake else "LIKELY AUTHENTIC"
    pdf.section_body(
        f"Analysis ID: {analysis_id}\n"
        f"Date: {now}\n"
        f"Verdict: {verdict}\n"
        f"Overall Authenticity Score: {authenticity_score:.1f}%"
    )

    # 2. Deepfake Detection
    pdf.section_title("2. Deepfake Detection Results")
    pdf.score_bar("Deepfake Confidence", deepfake_score)
    if deepfake_score > 70:
        pdf.section_body("High probability of synthetic or manipulated content detected.")
    elif deepfake_score > 40:
        pdf.section_body("Moderate indicators of manipulation. Manual review recommended.")
    else:
        pdf.section_body("Low risk of deepfake. Content appears genuine.")

    # 3. Identity Verification
    pdf.section_title("3. Identity Verification")
    if face_match_score is not None:
        pdf.score_bar("Face Match", face_match_score)
    else:
        pdf.section_body("Face matching: N/A (no registered identity provided)")
    if voice_match_score is not None:
        pdf.score_bar("Voice Match", voice_match_score)
    else:
        pdf.section_body("Voice matching: N/A")

    # 4. Authenticity Score
    pdf.section_title("4. Authenticity Score")
    pdf.score_bar("Authenticity", authenticity_score)

    # 5. AI Explanation
    pdf.section_title("5. AI Analysis Explanation")
    pdf.section_body(explanation)

    # 6. Conclusion
    pdf.section_title("6. Conclusion & Recommended Actions")
    if is_deepfake:
        pdf.section_body(
            "The analysis indicates the media is likely manipulated or synthetically generated.\n\n"
            "Recommended actions:\n"
            "- Do NOT rely on this media for identity verification.\n"
            "- Flag the source for further investigation.\n"
            "- Retain this report for legal/compliance records.\n"
            "- Request live identity verification (video call with liveness check)."
        )
    else:
        pdf.section_body(
            "The analysis indicates the media is likely authentic.\n\n"
            "Recommended actions:\n"
            "- This media can be used as supporting evidence for identity verification.\n"
            "- Retain this report for compliance records.\n"
            "- Periodically re-verify with updated samples."
        )

    # Save
    settings.REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    filename = f"report_{analysis_id}_{uuid.uuid4().hex[:8]}.pdf"
    filepath = str(settings.REPORTS_DIR / filename)
    pdf.output(filepath)
    return filepath
