import { jsPDF } from 'jspdf'
import type { Analysis, Identity } from '@/lib/api/types'

export function buildLegalReportPdf(
  identity: Identity | null,
  analysis: Analysis | null
): jsPDF {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const margin = 18
  let y = margin

  doc.setFillColor(15, 23, 42)
  doc.rect(0, 0, 210, 297, 'F')
  doc.setDrawColor(34, 211, 238)
  doc.setLineWidth(0.4)
  doc.line(margin, 28, 210 - margin, 28)

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.text('PersonaShield AI: Legal Authenticity Certificate', margin, y + 8)
  y += 18

  doc.setFontSize(10)
  doc.setTextColor(148, 163, 184)
  doc.text(`Generated: ${new Date().toLocaleString()}`, margin, y)
  y += 10

  doc.setTextColor(226, 232, 240)
  doc.setFontSize(11)
  doc.text('Branded proof bundle generated client-side via jsPDF.', margin, y)
  y += 14

  doc.setFontSize(12)
  doc.setTextColor(34, 211, 238)
  doc.text('Subject identity', margin, y)
  y += 7
  doc.setFontSize(10)
  doc.setTextColor(203, 213, 225)
  const name = identity?.name ?? 'Not registered'
  doc.text(`Name: ${name}`, margin, y)
  y += 6
  if (identity?.email) {
    doc.text(`Email: ${identity.email}`, margin, y)
    y += 6
  }
  doc.text(
    `Registration: ${identity?.created_at ? new Date(identity.created_at).toLocaleString() : 'N/A'}`,
    margin,
    y
  )
  y += 12

  doc.setFontSize(12)
  doc.setTextColor(167, 139, 250)
  doc.text('Analysis summary', margin, y)
  y += 7
  doc.setFontSize(10)
  doc.setTextColor(203, 213, 225)
  if (analysis) {
    doc.text(
      `Verdict: ${analysis.is_deepfake ? 'Synthetic / manipulated' : 'Likely authentic'}`,
      margin,
      y
    )
    y += 6
    doc.text(`Deepfake score: ${analysis.deepfake_score}%`, margin, y)
    y += 6
    if (analysis.face_match_score != null) {
      doc.text(`Face match: ${analysis.face_match_score}%`, margin, y)
      y += 6
    }
    if (analysis.voice_match_score != null) {
      doc.text(`Voice match: ${analysis.voice_match_score}%`, margin, y)
      y += 6
    }
    doc.text(`Authenticity score: ${analysis.authenticity_score}%`, margin, y)
    y += 6
    if (analysis.created_at) {
      doc.text(`Analyzed at: ${new Date(analysis.created_at).toLocaleString()}`, margin, y)
      y += 6
    }

    if (analysis.explanation) {
      y += 6
      doc.setFontSize(12)
      doc.setTextColor(251, 191, 36)
      doc.text('AI Explanation', margin, y)
      y += 7
      doc.setFontSize(9)
      doc.setTextColor(203, 213, 225)
      const lines = doc.splitTextToSize(analysis.explanation, 210 - margin * 2)
      doc.text(lines, margin, y)
      y += lines.length * 4.5
    }
  } else {
    doc.text('No analysis on file. Run Deepfake Scan to populate this section.', margin, y)
  }

  y += 16
  doc.setFontSize(9)
  doc.setTextColor(100, 116, 139)
  doc.text(
    'This document is generated by PersonaShield AI. Consult qualified counsel for legally enforceable instruments.',
    margin,
    y,
    { maxWidth: 210 - margin * 2 }
  )

  return doc
}
